// <auto-generated />
namespace CoffeeMachine.Data.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class seedingDrinkTypes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seedingDrinkTypes));
        
        string IMigrationMetadata.Id
        {
            get { return "201903261602281_seeding-DrinkTypes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
